# # Prettier
# name: Prettier

# on: [push]

# jobs:
#   build:
#     name: Prettier
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"

#       - name: Prettier
#         uses: borales/actions-yarn@v4
#         with:
#           cmd: format

#       # Start Here
#     # - run: yarn run test
