name: Update Base Branch

on:
  pull_request:
    types:
      - opened

jobs:
  update-base-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Installed Tools
        run: |
          echo "Installed tools:"
          ls /usr/bin

      - name: Set base branch to dev
        run: |
          TOKEN=$GITHUB_TOKEN
          BASE_BRANCH=dev
          PULL_REQUEST_URL=$(jq -r .pull_request.url $GITHUB_EVENT_PATH)

          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            -d "{\"base\":\"$BASE_BRANCH\"}" \
            "$PULL_REQUEST_URL"
